export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGIN_SOCIAL_NETWORKS = "LOGIN_SOCIAL_NETWORKS";
export const LOGIN_SOCIAL_NETWORKS_SUCCESS = "LOGIN_SOCIAL_NETWORKS_SUCCESS";
export const LOGIN_SOCIAL_NETWORKS_ERROR = "LOGIN_SOCIAL_NETWORKS_ERROR";

export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const RESET_PASSWORD_ERROR_MESSAGE = "RESET_PASSWORD_ERROR_MESSAGE";
export const RESET_PASSWORD_SUCCESS_MESSAGE = "RESET_PASSWORD_SUCCESS_MESSAGE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const UPDATE_PASSWORD = "RESET_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
